---

- name: Install Alfred
  homebrew_cask:
    name: alfred
    state: present

- name: Install Hazel
  homebrew_cask:
    name: hazel
    state: present

- name: Install BetterTouchTool
  homebrew_cask:
    name: bettertouchtool
    state: present

- name: Install AppCleaner
  homebrew_cask:
    name: appcleaner
    state: present

- name: Install Docker
  homebrew_cask:
    name: docker
    state: present

- name: Install Dropbox
  homebrew_cask:
    name: dropbox
    state: present

- name: Install TeamViewer
  homebrew_cask:
    name: teamviewer
    state: present

- name: Install Telegram
  homebrew_cask:
    name: telegram
    state: present

- name: Install Transmission
  homebrew_cask:
    name: transmission
    state: present

- name: Install VLC
  homebrew_cask:
    name: vlc
    state: present

- homebrew_tap:
    name: buo/cask-upgrade

- name: Install brew-cask-upgrade
  homebrew_cask:
    name: brew-cask-upgrade
    state: present
